# General
seed: 42
device: cuda
num_workers: 4

# Data
data:
  root_dir: "./data/PawPrint"
  data_dir: "PP+" # choice PP and PP+
  image_size: 224
  batch_size: 32
  num_classes: null  # automatically calculated
  use_weighted_sampling: true  # Enable balanced sampling

# Logging
wandb:
  project: "animal_pawprint_identification"
  entity: "inpyosong"
  log_environment_metrics: true

# Augmentation
augmentation:
  random_horizontal_flip: 0.5
  random_rotation: 15
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  gaussian_blur: 0.5

# Training
training:
  epochs: 100
  optimizer:
    name: "adamw"
    lr: 0.001
    weight_decay: 0.01
  scheduler:
    name: "cosine"
    T_max: 100
    eta_min: 1.0e-6

# Environment Analysis
environment:
  track_performance: true
  weighted_sampling: false # TODO: implement weighted sampling for environment

# Model
model:
  name: "resnet50"
  pretrained: true
  mode: "full"
  loss_weights:
    ce: 1.0  # Cross Entropy loss weight
  metric_learning:
    enabled: false
    weights:
      triplet: 1.0
      center: 0.1
      arcface: 0.1  # Set to 0 to disable specific loss
    triplet:
      margin: 0.3
      mining_strategy: "batch_hard"
    center:
      alpha: 0.1
    arcface:
      scale: 30.0
      margin: 0.5 