parent: base  # inherit base config

# Model specific settings
model:
  name: "resnet50"
  pretrained: true
  mode: "metric"  # Changed from "full" to "metric"
  use_local_features: true
  local_feature_type: "sift"  # or "orb"
  num_local_features: 2000
  loss_weights:
    ce: 0.7  # Cross Entropy loss weight
  metric_learning:
    weights:
      triplet: 0.0
      center: 0.0
      arcface: 0.3  # Set to 0 to disable specific loss
    triplet:
      margin: 0.3
      mining_strategy: "random"
    center:
      alpha: 0.1
    arcface:
      scale: 30.0
      margin: 0.5 
# Experiment specific settings
wandb:
  name: "resnet50_sift_arcface" 